spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.naver.com
    port: 465
    username: ants7021@naver.com
    password: TJ7LLYR9S2YE
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false